name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV


    - name: Zip Application
      run: |
        zip -r application.zip . -x "venv/*" "**/__pycache__/*" ".git/*" ".DS_Store"


    - name: Upload Application Artifact
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: application.zip

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Download Application Artifact
      uses: actions/download-artifact@v2
      with:
        name: application
        path: .

    - name: Deploy to AWS Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-1'
      run: |
        pip install awsebcli
        unzip application.zip -d deploy
        ls -l deploy/
        cd deploy
        eb init medicare-ai-model --platform python-3.11 --region $AWS_REGION --key $AWS_ACCESS_KEY_ID
        eb deploy Medicare-ai-model-env --region $AWS_REGION 