name: Deploy Flask App to Elastic Beanstalk

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your requirements file

      - name: Build the application (if necessary)
        run: # Replace with your build command (e.g., copy static files)

      - name: Create deployment archive
        uses: aws-actions/aws-zip@v1
        with:
          subdirectories: '**/*'  # Include all files in the deployment package
          artifact: deployment.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1  # Update with your desired AWS region

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/elasticbeanstalk-deploy@v1
        with:
          application-name: medicare-ai-model
          environment-name: Medicare-ai-model-env
          deployment-package: ${{ artifacts.deployment.zip }}