name: CI-CD-pipeline-to-AWS-ElasticBeanstalk
env:
  EB_BUCKET_NAME: "medicareai-model"
  EB_APPLICATION_NAME: "medicare-ai-model"
  EB_ENVIRONMENT_NAME: "Medicare-ai-model-env"
  DEPLOY_PACKAGE_NAME: "flaskapp_${{ github.sha }}.zip"
  AWS_REGION_NAME: "ap-southeast-1"
on: 
  push:
    branches: 
      - master
jobs:
  ci_part: 
    runs-on: ubuntu-latest
    steps: 
    - name: Git clone our repo
      uses: actions/checkout@v1   
    - name: Create ZIP deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*   
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
    - name: Copy Deployment package to S3 bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_BUCKET_NAME }}/
    - name: Print Happy Message for CI 
      run: echo "CI Pipeline part is finished successfully!"
  
  cd_part:
    runs-on: ubuntu-latest
    needs: ci_part
   
    steps:
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
   
    - name: create new EB application
      run: | 
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.EB_APPLICATION_NAME }} \
        --source-bundle S3Bucket="${{ env.EB_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
        --version-label "Ver-${{ github.sha }}" \
        --description "CommitSHA-${{ github.sha }}"
    
    - name: Deploy new EB Application Version
      run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}" 
    
    - name: Print Happy message for CD part 
      run: echo "CD pipeline finished sucessfully!"